application: tepco-usage-api
version: 1
runtime: python
api_version: 1

handlers:
- url: /update_from_tepco
  script: app.py
  login: admin
- url: /latest.json
  script: app.py
- url: /\d{4}/\d{1,2}/\d{1,2}/\d{1,2}.json
  script: app.py
- url: /\d{4}/\d{1,2}/\d{1,2}.json
  script: app.py
- url: /\d{4}/\d{1,2}.json
  script: app.py
- url: /quick.txt
  script: app.py
- url: /
  script: app.py
- url: /static/.*
  static_files: static/\1
  upload: static/(.*)
- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

builtins:
- datastore_admin: on
